In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets
import pandas as pd

In [4]:
data = pd.read_csv('iris_1D.csv')
data

Petal_Length  Label
0           1.4    0.0
1           1.0    0.0
2           1.5    0.0
3           3.1    1.0
4           3.8    1.0
5           4.1    1.0

In [26]:
# get x
x_data = data['Petal_Length'].to_numpy()
x_data = x_data.reshape(6, 1)
print(x_data)

[[1.4]
 [1. ]
 [1.5]
 [3.1]
 [3.8]
 [4.1]]


In [27]:
# get y
y_data = data['Label'].to_numpy()
print(y_data)

[0. 0. 0. 1. 1. 1.]


In [28]:
# unknown input
x_test = [[2.4]]

### Way 1

In [38]:
# get model
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_data, y_data)

KNeighborsClassifier(n_neighbors=3)

In [39]:
y_pred = classifier.predict(x_test)
print(y_pred)

[0.]


### Way 2

In [40]:
# get model
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=6)
classifier.fit(x_data, y_data)

KNeighborsClassifier(n_neighbors=6)

In [41]:
y_pred = classifier.kneighbors(x_test)
print(y_pred)

(array([[0.7, 0.9, 1. , 1.4, 1.4, 1.7]]), array([[3, 2, 0, 1, 4, 5]], dtype=int64))


In [35]:
classifier.classes_[classifier._y[3]]

1.0