In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets
import pandas as pd

In [2]:
data = pd.read_csv('iris_2D.csv')
data

Petal_Length  Petal_Width  Label
0           1.4          0.2    0.0
1           1.3          0.4    0.0
2           1.4          0.3    0.0
3           4.0          1.0    1.0
4           4.7          1.4    1.0
5           3.6          1.3    1.0

In [3]:
# get x
x_data = data[['Petal_Length', 'Petal_Width']].to_numpy()
x_data = x_data.reshape(6, 2)
print(x_data)

[[1.4 0.2]
 [1.3 0.4]
 [1.4 0.3]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]]


[0. 0. 0. 1. 1. 1.]


In [5]:
# unknown input
x_test = [[2.6, 0.7]]

### Way 1

In [6]:
# get model
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=1)
classifier.fit(x_data, y_data)

KNeighborsClassifier(n_neighbors=1)

In [7]:
y_pred = classifier.predict(x_test)
print(y_pred)

[1.]


### Way 2

In [8]:
# get model
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=6)
classifier.fit(x_data, y_data)

KNeighborsClassifier(n_neighbors=6)

In [9]:
y_pred = classifier.kneighbors(x_test)
print(y_pred)

(array([[1.16619038, 1.26491106, 1.3       , 1.33416641, 1.43178211,
        2.21359436]]), array([[5, 2, 0, 1, 3, 4]], dtype=int64))


E:\SoftInstallation\conda\envs\basic_env\lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
found 0 physical cores < 1
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "E:\SoftInstallation\conda\envs\basic_env\lib\site-packages\joblib\externals\loky\backend\context.py", line 282, in _count_physical_cores
    raise ValueError(f"found {cpu_count_physical} physical cores < 1")


In [55]:
classifier.classes_[classifier._y[3]]

1.0