## in cm

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets
import pandas as pd

data = pd.read_csv('iris_2D.csv')

# get x
x_data = data[['Petal_Length', 'Petal_Width']].to_numpy()
x_data = x_data.reshape(6, 2)
print(x_data)

# get y
y_data = data['Label'].to_numpy()
print(y_data)

[[1.4 0.2]
 [1.3 0.4]
 [1.4 0.3]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]]
[0. 0. 0. 1. 1. 1.]


In [6]:
# get model
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=6)
classifier.fit(x_data, y_data)

# unknown input
x_test = [[2.6, 0.7]]
y_pred = classifier.kneighbors(x_test)
print(y_pred)

(array([[1.16619038, 1.26491106, 1.3       , 1.33416641, 1.43178211,
        2.21359436]]), array([[5, 2, 0, 1, 3, 4]], dtype=int64))


## in mm

In [8]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets
import pandas as pd

data = pd.read_csv('iris_2D_mm.csv')

# get x
x_data = data[['Petal_Length', 'Petal_Width']].to_numpy()
x_data = x_data.reshape(6, 2)
print(x_data)

# get y
y_data = data['Label'].to_numpy()
print(y_data)

[[ 1.4  2. ]
 [ 1.3  4. ]
 [ 1.4  3. ]
 [ 4.  10. ]
 [ 4.7 14. ]
 [ 3.6 13. ]]
[0. 0. 0. 1. 1. 1.]


In [9]:
# get model
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=6)
classifier.fit(x_data, y_data)

# unknown input
x_test = [[2.6, 7.0]]
y_pred = classifier.kneighbors(x_test)
print(y_pred)

(array([[3.26955654, 3.31058907, 4.1761226 , 5.14198405, 6.08276253,
        7.30821456]]), array([[1, 3, 2, 0, 5, 4]], dtype=int64))
