In [3]:
import numpy as np
import torch
import tensorflow as tf

In [5]:
arr_zeros = np.zeros((3, 4))

print(arr_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
tensor_zeros = torch.zeros((3, 4))

print(tensor_zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [7]:
tf_zeros = tf.zeros((3,4))
print(tf_zeros)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)
