In [2]:
import numpy as np
import tensorflow as tf
arr_1 = np.array([[1, 2], [3, 4]])
arr_1

array([[1, 2],
       [3, 4]])

In [5]:
arr_transposed_1 = np.transpose(arr_1)
arr_transposed_1

array([[1, 3],
       [2, 4]])

In [6]:
arr_transposed_2 = arr_1.T
arr_transposed_2

array([[1, 3],
       [2, 4]])

In [3]:
tensor_1 = tf.constant([[1,2], [3, 4]])
tensor_1


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [4]:
tensor_transposed = tf.transpose(tensor_1)
tensor_transposed

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]])>

In [7]:
arr = np.array([[1,2,3],[4,5,6]])
total_sum = np.sum(arr)
column_sum = np.sum(arr, axis=0)
row_sum = np.sum(arr, axis=1)
print(total_sum)
print(column_sum)
print(row_sum)

21
[5 7 9]
[ 6 15]


In [8]:
tensor_sum = tf.reduce_sum(tensor_1)
tensor_sum_axis_0 = tf.reduce_sum(tensor_1, axis=0)
tensor_sum_axis_1 = tf.reduce_sum(tensor_1, axis=1)
print(tensor_sum)
print(tensor_sum_axis_0)
print(tensor_sum_axis_1)

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor([3 7], shape=(2,), dtype=int32)
