In [2]:
# Câu 3

import numpy as np

arr = np.arange(0, 10)
print(arr[arr % 2 == 1])

[1 3 5 7 9]


In [1]:
# Câu 4
import numpy as np

arr = np.arange(0, 10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [3]:
# Câu 5
import numpy as np

arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
# Câu 6
import numpy as np

arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
print(" Result : \n", c)

 Result : 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [5]:
# Câu 7
import numpy as np

arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=1)
print("C = ", c)

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [6]:
# Câu 8
import numpy as np

arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [7]:
# Câu 9
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
print(" result ", a[index])

 result  [ 6  9 10]


In [8]:
# Câu 10
import numpy as np


def maxx(x, y):
    if x >= y:
        return x
    else:
        return y


a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


In [9]:
# Câu 11
import numpy as np

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print(" Result ", np.where(a < b, b, a))

 Result  [6 7 9 8 9 7 5]


In [16]:
# Câu 12
# Download image
# !gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
import numpy as np

img = mpimg.imread("./dog.jpeg")
R = img[:, :, 0]
G = img[:, :, 1]
B = img[:, :, 2]

gray_img_01 = (np.maximum(np.maximum(R, G), B) + np.minimum(np.minimum(R, G), B)) / 2
gray_img_01[0, 0]

102.5

In [27]:
# Câu 13
import matplotlib.image as mpimg

img = mpimg.imread("./dog.jpeg")
gray_img_02 = np.mean([R, G, B], axis=0)
gray_img_02[0, 0]

107.66666666666667

In [21]:
# Câu 14
import matplotlib.image as mpimg

img = mpimg.imread("./dog.jpeg")
gray_img_03 = 0.21 * R + 0.72 * G + 0.07 * B
gray_img_03[0, 0]

126.22999999999999

In [36]:
# Câu 15
# Download data
# !gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd

df = pd.read_csv("./advertising.csv")
data = df.to_numpy()
print(np.max(data[:, 3]))
print(np.argmax(data[:, 3]))

27.0
175


In [38]:
# Câu 16
import pandas as pd

df = pd.read_csv("./advertising.csv")
data = df.to_numpy()
print(np.mean(data[:, 0]))

147.0425


In [42]:
# Câu 17
import pandas as pd

df = pd.read_csv("./advertising.csv")
data = df.to_numpy()
print(np.sum(data[:, 3] >= 20))

40


In [44]:
# Câu 18
import pandas as pd

df = pd.read_csv("./advertising.csv")
data = df.to_numpy()
tv_column = data[:, 0]
radio_column = data[:, 1]
newspaper_column = data[:, 2]
sales_column = data[:, 3]

print(np.mean(radio_column[sales_column >= 15]))

26.22293577981651


In [45]:
# Câu 19
import pandas as pd

df = pd.read_csv("./advertising.csv")
data = df.to_numpy()
tv_column = data[:, 0]
radio_column = data[:, 1]
newspaper_column = data[:, 2]
sales_column = data[:, 3]

print(np.sum(sales_column[newspaper_column > np.mean(newspaper_column)]))

1405.1


In [47]:
# Câu 20
import pandas as pd

df = pd.read_csv("./advertising.csv")
data = df.to_numpy()
tv_column = data[:, 0]
radio_column = data[:, 1]
newspaper_column = data[:, 2]
sales_column = data[:, 3]

mean_sales = np.mean(sales_column)
scores = []
for sale in sales_column:
    if sale > mean_sales:
        scores.append("Good")
    elif sale < mean_sales:
        scores.append("Bad")
    else:
        scores.append("Average")

print(f"{scores[7:10]}")

['Bad', 'Bad', 'Good']


In [51]:
# Câu 21
import pandas as pd

df = pd.read_csv("./advertising.csv")
data = df.to_numpy()
tv_column = data[:, 0]
radio_column = data[:, 1]
newspaper_column = data[:, 2]
sales_column = data[:, 3]

mean_sales = np.mean(sales_column)
closest_sales = sales_column[np.abs(sales_column - mean_sales).argmin()]
scores_closest = []
for sale in sales_column:
    if sale > closest_sales:
        scores_closest.append("Good")
    elif sale < closest_sales:
        scores_closest.append("Bad")
    else:
        scores_closest.append("Average")

# In kết quả scores_closest[7:10]
print(f"{scores_closest[7:10]}")

['Bad', 'Bad', 'Good']
